### ISSUE TITLE
seq_len gives generator has no len error

### ISSUE THREAD

**Issue by AnnaWegmann** [zouharvi/tokenization-scorer#5]
Getting `TypeError: object of type 'generator' has no len()` when calling `tokenization_scorer.score("Hello there", metric="seq_len")`. Same for different inputs (list of lists etc.). Found a workaround by calling _seq_len directly, I think, st no generator is created from, e.g., a list of lists. `_seq_len([['Hello', 'there']])`.

**Comment by zouharvi** [comment]
Hi Anna! Thanks for reporting this issue. I just pushed `v1.1.2` that fixes it. :slightly_smiling_face: Could you update (`pip3 install -U tokenization-scorer`) and also confirm it on your end?

Before:
```
$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score('Hello there', metric='seq_len'))"
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 54471.48it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vilda/tokenization-scorer/tokenization_scorer/__init__.py", line 27, in score
    score_val = get_metric(metric)(text, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilda/tokenization-scorer/tokenization_scorer/metrics.py", line 21, in _seq_len
    return -np.average([len(l) for l in text])
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilda/tokenization-scorer/tokenization_scorer/metrics.py", line 21, in <listcomp>
    return -np.average([len(l) for l in text])
                        ^^^^^^
TypeError: object of type 'generator' has no len()
```


After:
```
$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score('Hello there', metric='seq_len'))"
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56679.78it/s]
-5.0
```

**Comment by zouharvi** [comment]
Actually hold on this introduced another bug.

**Comment by zouharvi** [comment]
Should return correct values now with `v1.1.4`:

```
python3 -c "import tokenization_scorer; print(tokenization_scorer.score('Hello there', metric='seq_len'))"
-2.0

$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score('Hell @@o the @re', metric='seq_len'))"
-4.0

$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score(['Hell @@o the @re', 'Another line'], metric='seq_len'))"
-3.0
```

**Comment by AnnaWegmann** [comment]
Works now! Thanks :)

**Comment by AnnaWegmann** [comment]
FYI:

```
$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in ['Hell @@o the @re', 'Another line']), metric='seq_len'))"
-3.0
$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in [['Hell @@o' ,'the' ,'@re'], ['Another', 'line']]), metric='seq_len'))"
-1.2
```

give different results. I assume the use case you intend is the first?

**Comment by zouharvi** [comment]
Oh no. Let me look into that.

**Comment by zouharvi** [comment]
The reason why this simplest metric is broken so much is because it tries to compute average tokens per line. But what is a line is kinda tough to define with such a permissive input. For that reason I now turned it in v1.1.5 into just total number of subwords:

```
$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in ['Hell @@o the @re', 'Another line']), metric='seq_len'))"
-6

vilda@kohlrabi:~/tokenization-scorer$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in [['Hell @@o' ,'the' ,'@re'], ['Another', 'line']]), metric='seq_len'))"
-6

vilda@kohlrabi:~/tokenization-scorer$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in [['Hell @@o the @re'], ['Another', 'line']]), metric='seq_len'))"
-6

vilda@kohlrabi:~/tokenization-scorer$ python3 -c "import tokenization_scorer; print(tokenization_scorer.score((line for line in ['Hell @@o the @re', 'Another', 'line']), metric='seq_len'))"
-6
```

This is kinda less informative but hopefully more robust? What do you think?

**Comment by AnnaWegmann** [comment]
Ah I get it. Thanks.

Hm. So not averaged anymore over lines now? Makes it less sequence length and more doc_len, no? I'd prefer having sth averaged over lines but then making necessary assumptions of what a line probably is. Like highest level iteration is the lines and lower levels when flattened out give the subwords.

**Comment by zouharvi** [comment]
Resolved with your merge request in v1.1.6. :slightly_smiling_face:

**Comment by AnnaWegmann** [comment]
✅ thanks!

Op vr 22 nov 2024 om 16:30 schreef Vilém Zouhar ***@***.***>

**Comment by zouharvi** [comment]
I finally added automatic tests to the package to catch this. The result should be visible as a badge on README.
